project_id = "cbkexpjttanvpqxtzeie"

[functions.send-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false
